In [3]:
pip install Faker

Collecting FakerNote: you may need to restart the kernel to use updated packages.

  Downloading Faker-25.1.0-py3-none-any.whl (1.8 MB)
     ---------------------------------------- 1.8/1.8 MB 539.5 kB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in c:\users\lenovo\anaconda3\anaconda\lib\site-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\anaconda\lib\site-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Installing collected packages: Faker
Successfully installed Faker-25.1.0

WARNING: Error parsing requirements for colorama: 'utf-8' codec can't decode byte 0xc9 in position 6: invalid continuation byte in METADATA file at path: c:\users\lenovo\anaconda3\anaconda\lib\site-packages\colorama-0.4.5.dist-info\METADATA

## Create Fake Datasets

In [3]:
from faker import Faker
import pandas as pd
import random

# Initialize Faker
fake = Faker()

In [14]:
customers = pd.DataFrame({
    'Customer_ID': range(1001, 1501),
    'First_Name': [fake.first_name() for _ in range(500)],
    'Last_Name': [fake.last_name() for _ in range(500)],
    'Email': [fake.email() for _ in range(500)],
    'Phone': [fake.phone_number() for _ in range(500)],
    'Address': [fake.address() for _ in range(500)]
})

# Generate fake data for orders (at least 500 rows)
orders = pd.DataFrame({
    'Order_ID': range(10001, 10501),
    'Customer_ID': [random.randint(1001, 1500) for _ in range(500)],
    'Product_ID': [random.randint(1, 50) for _ in range(500)],
    'Quantity': [random.randint(1, 10) for _ in range(500)],
    'Order_Date': [fake.date_between(start_date='-1y', end_date='today') for _ in range(500)]
})

# Generate fake data for shipments (at least 500 rows)
Shippers = pd.DataFrame({
    'Shippers_ID': range(100001, 100501),
    'Order_ID': [random.randint(10001, 10500) for _ in range(500)],
    'Ship_Date': [fake.date_between(start_date='-1y', end_date='today') for _ in range(500)],
    'Shipping_Method': [fake.word() for _ in range(500)],
    'Shipping_Cost': [round(random.uniform(5, 50), 2) for _ in range(500)]
})

# Generate fake data for payments (at least 500 rows)
payments = pd.DataFrame({
    'Payment_ID': range(1000001, 1000501),
    'Order_ID': [random.randint(10001, 10500) for _ in range(500)],
    'Amount': [round(random.uniform(50, 1000), 2) for _ in range(500)],
    'Payment_Date': [fake.date_between(start_date='-1y', end_date='today') for _ in range(500)]
})

# Generate fake data for employees (at least 500 rows)
Category = pd.DataFrame({
    'Category_ID': range(10001, 10501),
    'Category_Name': [fake.first_name_male() for _ in range(250)] + [fake.first_name_female() for _ in range(250)],
})

# Generate fake data for suppliers (at least 500 rows)
suppliers = pd.DataFrame({
    'Supplier_ID': range(1001, 1501),
    'Supplier_Name': [fake.company() for _ in range(500)],
    'Contact_Name': [fake.name() for _ in range(500)],
    'Email': [fake.email() for _ in range(500)],
    'Phone': [fake.phone_number() for _ in range(500)],
    'Address': [fake.address() for _ in range(500)]
})

# Generate fake data for purchases (at least 500 rows)
orderdetails = pd.DataFrame({
    'orderdetails_ID': range(100001, 100501),
    'Order_ID':range(100001, 100501)
    'orderders_ID': range(100001, 100501)
    'Product_ID': [random.randint(1, 50) for _ in range(500)],
    'Supplier_ID': [random.randint(1001, 1050) for _ in range(500)],
    'Quantity': [random.randint(10, 100) for _ in range(500)],
    'Purchase_Date': [fake.date_between(start_date='-1y', end_date='today') for _ in range(500)]
})

# Generate fake data for inventory (at least 500 rows)
inventory = pd.DataFrame({
    'Inventory_ID': range(1000001, 1000501),
    'Product_ID': [random.randint(1, 50) for _ in range(500)],
    'Quantity': [random.randint(1, 100) for _ in range(500)]
})4

In [15]:
purchases.columns

Index(['Purchase_ID', 'Product_ID', 'Supplier_ID', 'Quantity',
       'Purchase_Date'],
      dtype='object')

In [16]:

# Set primary key for products DataFrame
products.set_index('Product_ID', inplace=True)

# Add foreign keys to other DataFrames
customers['Product_ID'] = [random.randint(1, 50) for _ in range(500)]
orders['Product_ID'] = [random.randint(1, 50) for _ in range(500)]
shipments['Product_ID'] = [random.randint(1, 50) for _ in range(500)]
payments['Product_ID'] = [random.randint(1, 50) for _ in range(500)]
employees['Product_ID'] = [random.randint(1, 50) for _ in range(500)]
suppliers['Product_ID'] = [random.randint(1, 50) for _ in range(500)]
purchases['Product_ID'] = [random.randint(1, 50) for _ in range(500)]
inventory['Product_ID'] = [random.randint(1, 50) for _ in range(500)]

# Set primary keys for other DataFrames
customers.set_index('Customer_ID', inplace=True)
orders.set_index('Order_ID', inplace=True)
shipments.set_index('Shipment_ID', inplace=True)
payments.set_index('Payment_ID', inplace=True)
employees.set_index('Employee_ID', inplace=True)
suppliers.set_index('Supplier_ID', inplace=True)
purchases.set_index('Purchase_ID', inplace=True)
inventory.set_index('Inventory_ID', inplace=True)

In [17]:
purchases

             Product_ID  Supplier_ID  Quantity Purchase_Date
Purchase_ID
100001               41         1038        87    2024-04-24
100002               50         1048        72    2024-03-05
100003                6         1044        45    2023-10-09
100004                2         1011        40    2024-02-11
100005               46         1028        61    2024-01-10
...                 ...          ...       ...           ...
100496               25         1039        63    2023-12-28
100497               25         1047        87    2023-11-25
100498               14         1043        21    2023-12-19
100499               14         1040        55    2023-11-19
100500               49         1002        97    2023-12-12

[500 rows x 4 columns]

In [19]:
# Convert customers DataFrame to CSV
customers.to_csv('customers.csv', index=False)

# Convert orders DataFrame to CSV
orders.to_csv('orders.csv', index=False)

# Convert shipments DataFrame to CSV
shipments.to_csv('shipments.csv', index=False)

# Convert payments DataFrame to CSV
payments.to_csv('payments.csv', index=False)

# Convert employees DataFrame to CSV
Category.to_csv('Categories.csv', index=False)

# Convert suppliers DataFrame to CSV
suppliers.to_csv('suppliers.csv', index=False)

# Convert purchases DataFrame to CSV
purchases.to_csv('purchases.csv', index=False)

In [24]:
# Generate product data
def generate_product_data(num_rows):
    product_data = []
    for _ in range(num_rows):
        product_name = fake.word() + ' Pipe'
        diameter = fake.random_int(min=1, max=24)  # Random diameter between 1 and 24 inches
        material = fake.word()  # Fake material name
        price = round(fake.random_number(digits=2), 2)  # Random price with 2 decimal places
        supplier_id = random.randint(1001, 1050)  # Random supplier ID
        category = fake.word()  # Fake category
        product_data.append({'Product Name': product_name, 'Diameter (inches)': diameter,
                             'Material': material, 'Price ($)': price, 'Supplier_ID': supplier_id,
                             'Category': category})
    return product_data

# Generate product data for 500 rows
num_rows = 500
product_data = generate_product_data(num_rows)

# Create DataFrame
product_df = pd.DataFrame(product_data)

# Display DataFrame
print(product_df.head())

         Product Name  Diameter (inches)  Material  Price ($)  Supplier_ID  \
0          guess Pipe                  5     image         58         1050
1          enjoy Pipe                 12    former         52         1025
2            eat Pipe                 18      push         60         1046
3  international Pipe                 19      such         87         1049
4          civil Pipe                  5  analysis         69         1017

    Category
0        see
1      place
2      young
3       sell
4  direction

In [25]:
product_df.to_csv('product_df.csv', index=False)